<center> <img src='https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png'/></center>
<center><h2>Best NumPy Functions For Data Science </h2></center>

NumPy stands for numerical python and is a library in python that adds the functionality of large multi-dimensional arrays and matrices. It works as a building block for all the libraries in pydata ecosystem. NumPy is one of the most useful tools for a data scientist that uses python. It can handle large-size data efficiently. One of the biggest reasons to use NumPy is its arrays and multiple scientific functions to work with arrays.

#### **========𝗧𝗔𝗕𝗟𝗘 𝗢𝗙 𝗖𝗢𝗡𝗧𝗘𝗡𝗧========**
- Array Creation Methods
- Array Operations
- Replacing Values Inside Array
- Set Operations
- Splitting
- Stacking
- Comparing Two Arrays
- Repeating Array Elements
- Einstein Summation Conventions
- Statistical Analysis
- Array Printing Options
- Save and Load Array Data

# Array Creation Methods

## 1. Array
It is used to create one-dimensional or multidimensional arrays from scratch.<br>
`array(Object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)`


**Important params**<br>
`dtype`: desired data type for the resultant array.<br>
`ndim`: Specify the minimum number of dimensions for the resultant array.

In [2]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

You can also use this function to convert series or dataframes into a NumPy array.

In [2]:
import pandas as pd
sex = pd.Series(['Male','Female','Female'])
np.array(sex)

array(['Male', 'Female', 'Female'], dtype=object)

### 2. Linspace
Creates an array with evenly spaced float numbers over a specified interval.<br>
`np.linspace(start, stop, num = 50, endpoint=True, retstep=False, dtype=None,axis=0)`

**Important params**<br>
`start`: starting index<br>
`end`: last index<br>
`num`: number of samples to generate, default = 50.

In [4]:
np.linspace(10,100,11)

array([ 10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])

### 3. Arange
Return evenly spaced integer values over a given interval with some step size.<br>
`np.arrange(star, stop, step, dtype=None)`

**Important params**<br>
`step`: Space between values.

In [6]:
np.arange(1,10,3)

array([1, 4, 7])

### 4. Uniform Samples
Generate a random sample from a uniform distribution between lower and higher limit values.<br>
`np.uniform(low=0.0, high=1.0, size=None)`

In [8]:
np.random.uniform(5,10,size=4)

array([7.54543752, 8.31577255, 7.41378061, 6.07851965])

In [9]:
np.random.uniform(size=5)

array([0.50321276, 0.1657569 , 0.65681053, 0.52885359, 0.72324676])

In [10]:
np.random.uniform(size = (2,3))

array([[0.9645747 , 0.12858925, 0.37999948],
       [0.12502306, 0.96450191, 0.30106948]])

### 5. Random.randint
Generate n random integer samples within a range.<br>
`np.random.randiant(low, high=None, size=None, dtype=int)`

In [11]:
np.random.randint(5,15,10)

array([ 7, 14,  9, 10, 12,  5,  6, 11,  7, 14], dtype=int32)

In [15]:
np.random.random(5)

array([0.38281068, 0.03978169, 0.68758596, 0.14063184, 0.37047046])

### 7. Logspace
Generate evenly spaced numbers on a log scale.<br>
`np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)`

**Important params**<br>
`start`: starting value of the sequence.<br>
`end`: last value of the sequence.<br>
`endpoint`: if True, the last sample will be included in the sequence.<br>
`base`: The base of the log space. default is 10.

In [16]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

### 8. Array of zero
np.zeroes function helps to create an array of 0<br>
`np.zero(shape, dtype=float, order='C')`

**Important params**<br>
`shape`: shape of the resultant array.<br>
`dtype`: desired data type of resultant array. ‘int’ or default ‘float’

In [19]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 9. Array of Ones
np.ones function helps to create an array of 1.<br>
`np.ones(shape, dtype=None, order='C')`

In [21]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 10. Array of k Random Value
Creates an n-dimensional array of a random value.<br>
`np.full(shape, fill_value, dtype=None)`<br>

**Important params**<br>
`fill_value`: Random value to fill inside the array.

In [23]:
np.full((2,4), fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

### 11. Identity
Create an identity matrix with specified dimensions.<br>
`np.identity(n, dtype=None)`

In [24]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

# Array Operations

### 12. Min
Return the minimum value from the array.<br>
`np.min(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)`

**Important params**<br>
`axis`: axis along which to operate.<br>
`out`: alternative array to store the output.

In [26]:
arr = np.array([1,1,2,3,4,4,5,5,6,6,2,2])
print(np.min(arr))

1


### 13. Max
Return the maximum value from the array.<br>
`np.max(a, axis=None, out=None)`

In [27]:
np.max(arr)

np.int64(6)

### 14. Unique
Return an array with all the unique elements sorted.<br>
`np.unique(arr, return_index=False, return_inverse=False, return_counts=False, axis=None)`

**Important params**<br>
`return_index`: if True, return the indices of the array.<br>
`return_inverse`: if True, return the indices of the unique array.<br>
`return_counts`: if True, return the number of times each unique element appears inside the array.<br>
`axis`: The axis to operate on. By default, the array is considered flattened.

In [28]:
np.unique(arr, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 3, 1, 2, 2, 2]))

### 15. Mean
It is used to get the mean of the array.<br>
`np.mean(a, axis=None, dtype=None, out=None)`

In [29]:
np.mean(arr, dtype=int)

np.int64(3)

### 16. Median
Return the median value of the array.<br>
`np.median(a, axis=None, out=None)`

In [34]:
arr = np.array([[1,2,3],[5,9,5]])
np.median(arr)

np.float64(4.0)

### 17. Digitize
Return the indices of the bins to which each value in the input array belongs.<br>
`np.digitize(x, bins, right=False)`

**Important params**<br>
`bins`: Array of bins.<br>
`right`: Indicates whether the interval includes the right or left bin edge.

In [35]:
a = np.array([-0.9, 0.5, 0.9, 1, 1.2, 1.4, 3.6, 4.7, 5.7])
bins = np.array([0,1,2,3])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 4, 4, 4])

```
Exp        Value
x < 0     :   0
0 <= x <1 :   1
1 <= x <2 :   2
2 <= x <3 :   3
3 <=x     :   4
Compares -0.9 to 0, here x < 0 so Put 0 in resulting array.
Compares  0.5 to 0, here 0 <= x <1 so Put 1.
.
Compares 5.4 to 4, here 3<=x so Put 4
```

### 18. Reshape
It is one of the most used functions of NumPy. It Returns an array containing the same data with a new shape.<br>
`np.reshape(shape)`

In [41]:
a = np.random.randint(12, size=(4,3))
a

array([[ 5,  2,  9],
       [ 0,  6,  6],
       [ 0,  2,  0],
       [ 9, 10,  7]], dtype=int32)

In [42]:
a.reshape(3,4)

array([[ 5,  2,  9,  0],
       [ 6,  6,  0,  2],
       [ 0,  9, 10,  7]], dtype=int32)

In [45]:
a.reshape(-1)

array([ 5,  2,  9,  0,  6,  6,  0,  2,  0,  9, 10,  7], dtype=int32)

### 19. Expand Dimensions
It is used to expand the dimensions of an array. This method is useful for creating sample test data for testing a machine learning model.<br>
`np.expand_dims(a, axis)`

In [46]:
arr = np.array([8, 14, 15, 1, 6, 11, 4, 9, 4, 12, 13, 13, 11])
np.expand_dims(arr, axis=0)

array([[ 8, 14, 15,  1,  6, 11,  4,  9,  4, 12, 13, 13, 11]])

In [47]:
np.expand_dims(arr, axis=1)

array([[ 8],
       [14],
       [15],
       [ 1],
       [ 6],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [12],
       [13],
       [13],
       [11]])

## 20. Squeeze
Reduce the dimension of an array by removing single-dimensional entrie.<br>
`np.squeeze(a, axis=None)`

In [48]:
arr = np.array([[8],[14],[1],[8],[11],[4],[9],[4],[1],[13],[13],[11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

### 21. Count Non-Zero
Count all the non-zero elements and return their count.<br>
`np.count_nonzero(a, axis=None, *, keepdims=False)`

In [3]:
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

np.int64(3)

### 22. argwhere
Find and return all the indices of non-zero elements.<br>
`np.argwhere(a)`

In [5]:
a = np.array([0,0,1,1,1,0])
np.argwhere(a)

array([[2],
       [3],
       [4]])

### 23. argmax & argmin
argmax returns the index of the max element from the array. It can be used to get the index of high probability predicted labels in multiclass image classification problems.<br>
`np.argmax(a, axis=None, out=None)`

In [6]:
arr = np.array([[0.12,0.64,0.19,0.05]])
np.argmax(arr)

np.int64(1)

argmin will return the index of the lowest element from the array.<br>
`np.argmin(a, axis=None, out=None)`

In [7]:
np.argmin(min)

np.int64(0)

### 24. Sort
Sort the array and return.<br>
`np.sort(a, axis=-1, kind=None, order=None)`

**Important params**<br>
`kind`: Sorting algorithm to use. {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}

In [8]:
arr = np.array([2,3,1,7,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

### 25. Abs
Return the absolute values of elements inside an array. It is useful when an array contains negative values.

In [9]:
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

### 26. Round
Round the float values to a specified number of decimal points.<br>
`np.round(a, decimals=0, out=None)`

**Important params**<br>
`decimals`: Number of decimals point to keep.

In [10]:
a = np.random.random(size=(3,4))
a

array([[0.31671396, 0.08358254, 0.29353572, 0.35314265],
       [0.93329822, 0.84102269, 0.9604354 , 0.86254484],
       [0.86525753, 0.56618658, 0.80851893, 0.87694445]])

In [13]:
np.round(a, decimals=0)

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.round(a, decimals=1)

array([[0.3, 0.1, 0.3, 0.4],
       [0.9, 0.8, 1. , 0.9],
       [0.9, 0.6, 0.8, 0.9]])

### 27. Clip
It is used to keep the values of an array within a range.

In [15]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [16]:
arr.clip(0,3)

array([0, 1, 0, 0, 3, 3, 3, 2, 3])

In [18]:
arr.clip(4,5)

array([4, 4, 4, 4, 5, 5, 5, 4, 4])

---

## Replacing Values Inside Array

### 28. Where
Return elements from an array where a condition satisfies.<br>
`np.where(condition, [x,y])`

**Important params**<br>
`condition`: condition to match. if true yield x otherwise y.

In [19]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.where(a>5)

(array([2, 2, 2, 3, 3, 3]), array([0, 1, 2, 0, 1, 2]))

```
'''
[2][0] ᴇʟᴇᴍᴇɴᴛ (2ɴꜱ ʀᴏᴡ 0ᴛʜ ᴄᴏʟᴜᴍɴ) 6 > 5, ʀᴇᴛᴜʀɴ
[2][1] ᴇʟᴇᴍᴇɴᴛ (2ɴᴅ ʀᴏᴡ 1ꜱᴛ ᴄᴏʟᴜᴍɴ) 7 > 5, ʀᴇᴛᴜʀɴ
.
[3][2] ᴇʟᴇᴍᴇɴᴛ (3ᴅ ʀᴏᴡ 2ɴᴅ ᴄᴏʟᴜᴍɴ) 11 > 5, ʀᴇᴛᴜʀɴ
'''
```

In [21]:
a[np.where(a>5)]

array([ 6,  7,  8,  9, 10, 11])

It can also be used to replace elements inside the panda’s data frame.

`np.where(data[feature].isnull(), 1, 0)`

```
Replace Null Values with 1 and other as 0
```

### 29. Put
Replaces specified elements of an array with given values.<br>
`np.put(a, ind, v)`

**Important params**<br>
`a`: array<br>
`ind`: indices to be replaced.<br>
`v`: values to place.

In [22]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [23]:
np.put(arr, [1,2], [6,7])
arr

array([1, 6, 7, 4, 5, 6])

### 30. Copyto
Copy the content of one array into another.<br>
`copyto(dst, src, casting='same_kind', where=True)`

**Important params**<br>
`dst`: array into which values are copied.<br>
`src`: array from which values are copied.


In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Before arr1",arr1)
print("Before arr2",arr1)
np.copyto(arr1,arr2)
print("After arr1",arr1)
print("After arr2",arr2)

Before arr1 [1 2 3]
Before arr2 [1 2 3]
After arr1 [4 5 6]
After arr2 [4 5 6]


## Set Operations

### 31. Retrieve Common Elements
`np.intersect1d` function returns all the unique values from both arrays in a sorted manner.<br>
`np.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)`

**Important params**<br>
`assume_unique`: if true, then input arrays are both assumed to be unique.<br>
`return_indices`: if true, then common elements indices are returned.

In [25]:
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([3,4,5,8,9,1])
np.intersect1d(ar1, ar2)

array([1, 3, 4, 5])

In [26]:
np.intersect1d(ar1, ar2, return_indices=True)

(array([1, 3, 4, 5]), array([0, 2, 3, 4]), array([5, 0, 1, 2]))

array([0, 2, 3, 4], dtype=int64) :- Indices of common elements inside first array.<br>
array([5, 0, 1, 2], dtype=int64) :- Indices of common elements inside second array.

### 32. Difference
`np.setdiff1d` function returns all the unique elements from array 1 that are not present in arr2.

In [27]:
a = np.array([1,7,3,2,4,1])
b = np.array([9,2,5,6,7,8])
np.setdiff1d(a,b)

array([1, 3, 4])

### 33. Extracts Unique Elements From Both Arrays
`setxor1d` function will return all the unique values from both arrays in sorted order.

In [28]:
a = np.array([1, 2, 3, 4, 6])
b = np.array([1, 4, 9, 4, 36])
np.setxor1d(a,b)

array([ 2,  3,  6,  9, 36])

### 34. Union
`union1d` function will combine both arrays into one.

In [29]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 5, 4, 36])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5, 36])

---

# Splitting

### 35. Horizontal Split
`hsplit` function will split the data horizontally into n equal parts.

In [30]:
A = np.array([[3, 4, 5, 2], [6, 7, 2, 6]])
np.hsplit(A,2) # splits the data into two equal parts

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [31]:
np.hsplit(A,4) # splits the data into four equal parts

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

### 36. Vertical Split
`vsplit` will split data vertically into n equal parts.

In [32]:
A = np.array([[3, 4, 5, 2], [6, 7, 2, 6]])
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

---

# Stacking

### 37. Horizontal Stacking
`hstack` will stack appends one array at the end of another.

In [33]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

### 38. Vertical Stacking
`vstack` will stack one array on top of another.

In [34]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

---

# Well Done! More to Add