# np.sort
Return a sorted copy of an array.<br>
https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([40, 46, 63, 47, 36, 58, 43, 31, 19, 52, 75, 64, 35, 95, 43],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 1, 50, 83, 55],
       [33, 16,  7, 15],
       [65, 90,  6, 10],
       [ 4, 21, 73, 80],
       [78, 58, 37, 78],
       [32, 87, 64, 90]], dtype=int32)

In [5]:
np.sort(a)

array([19, 31, 35, 36, 40, 43, 43, 46, 47, 52, 58, 63, 64, 75, 95],
      dtype=int32)

In [7]:
np.sort(a)[::-1]

array([95, 75, 64, 63, 58, 52, 47, 46, 43, 43, 40, 36, 35, 31, 19],
      dtype=int32)

In [8]:
np.sort(b,axis=0)

array([[ 1, 16,  6, 10],
       [ 4, 21,  7, 15],
       [32, 50, 37, 55],
       [33, 58, 64, 78],
       [65, 87, 73, 80],
       [78, 90, 83, 90]], dtype=int32)

# np.append
The numpy.append() appends values along the mentioned axis at the end of the array.<br>
https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
np.append(a,200)

array([ 40,  46,  63,  47,  36,  58,  43,  31,  19,  52,  75,  64,  35,
        95,  43, 200])

In [10]:
b

array([[ 1, 50, 83, 55],
       [33, 16,  7, 15],
       [65, 90,  6, 10],
       [ 4, 21, 73, 80],
       [78, 58, 37, 78],
       [32, 87, 64, 90]], dtype=int32)

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 1., 50., 83., 55.,  1.],
       [33., 16.,  7., 15.,  1.],
       [65., 90.,  6., 10.,  1.],
       [ 4., 21., 73., 80.,  1.],
       [78., 58., 37., 78.,  1.],
       [32., 87., 64., 90.,  1.]])

# np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.<br>
https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [12]:
# Code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.<br>
https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [16]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [17]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array<br>
https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [18]:
a.shape

(15,)

In [19]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
np.expand_dims(a,axis=1)

array([[40],
       [46],
       [63],
       [47],
       [36],
       [58],
       [43],
       [31],
       [19],
       [52],
       [75],
       [64],
       [35],
       [95],
       [43]], dtype=int32)

# np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.<br>
https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [21]:
a

array([40, 46, 63, 47, 36, 58, 43, 31, 19, 52, 75, 64, 35, 95, 43],
      dtype=int32)

In [22]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  5,  9, 10, 11, 13]),)

In [24]:
# replace all value > 50 with 0
np.where(a>50,0,a)

array([40, 46,  0, 47, 36,  0, 43, 31, 19,  0,  0,  0, 35,  0, 43],
      dtype=int32)

In [26]:
# replace all even number with 0
np.where(a%2 ==0 ,0,a)

array([ 0,  0, 63, 47,  0,  0, 43, 31, 19,  0, 75,  0, 35, 95, 43],
      dtype=int32)

# np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.<br>
https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [27]:
a

array([40, 46, 63, 47, 36, 58, 43, 31, 19, 52, 75, 64, 35, 95, 43],
      dtype=int32)

In [28]:
np.argmax(a)

np.int64(13)

In [29]:
b

array([[ 1, 50, 83, 55],
       [33, 16,  7, 15],
       [65, 90,  6, 10],
       [ 4, 21, 73, 80],
       [78, 58, 37, 78],
       [32, 87, 64, 90]], dtype=int32)

In [30]:
np.argmax(b,axis=0)

array([4, 2, 0, 5])

In [ ]:
# np.argmin
np.argmin(a)

np.int64(8)

# np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.<br>
https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [32]:
a

array([40, 46, 63, 47, 36, 58, 43, 31, 19, 52, 75, 64, 35, 95, 43],
      dtype=int32)

In [33]:
np.cumsum(a)

array([ 40,  86, 149, 196, 232, 290, 333, 364, 383, 435, 510, 574, 609,
       704, 747])

In [34]:
b

array([[ 1, 50, 83, 55],
       [33, 16,  7, 15],
       [65, 90,  6, 10],
       [ 4, 21, 73, 80],
       [78, 58, 37, 78],
       [32, 87, 64, 90]], dtype=int32)

In [37]:
np.cumsum(b,axis=0)

array([[  1,  50,  83,  55],
       [ 34,  66,  90,  70],
       [ 99, 156,  96,  80],
       [103, 177, 169, 160],
       [181, 235, 206, 238],
       [213, 322, 270, 328]])

In [38]:
# np.cumrod
np.cumprod(a)

array([                  40,                 1840,               115920,
                    5448240,            196136640,          11375925120,
               489164780160,       15164108184960,      288118055514240,
          14982138886740480,  1123660416505536000, -1872709638483902464,
        8242138947901620224,  8239948954852753408,  3829667658186915840])

# np.percentile
numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis.<br>
https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [39]:
a

array([40, 46, 63, 47, 36, 58, 43, 31, 19, 52, 75, 64, 35, 95, 43],
      dtype=int32)

In [40]:
np.percentile(a,100)

np.float64(95.0)

In [41]:
np.percentile(a,50)

np.float64(46.0)

In [42]:
np.median(a)

np.float64(46.0)

# np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.<br>
https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [43]:
a

array([40, 46, 63, 47, 36, 58, 43, 31, 19, 52, 75, 64, 35, 95, 43],
      dtype=int32)

In [44]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 0, 3, 5, 2, 2, 1, 0, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef
Return Pearson product-moment correlation coefficients.<br>
https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [45]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.<br>
https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [47]:
# code
a

array([40, 46, 63, 47, 36, 58, 43, 31, 19, 52, 75, 64, 35, 95, 43],
      dtype=int32)

In [48]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([40], dtype=int32)

# np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.<br>
https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [49]:
# code
a

array([40, 46, 63, 47, 36, 58, 43, 31, 19, 52, 75, 64, 35, 95, 43],
      dtype=int32)

In [50]:
np.flip(a)

array([43, 95, 35, 64, 75, 52, 19, 31, 43, 58, 36, 47, 63, 46, 40],
      dtype=int32)

In [51]:
b

array([[ 1, 50, 83, 55],
       [33, 16,  7, 15],
       [65, 90,  6, 10],
       [ 4, 21, 73, 80],
       [78, 58, 37, 78],
       [32, 87, 64, 90]], dtype=int32)

In [52]:
np.flip(b)

array([[90, 64, 87, 32],
       [78, 37, 58, 78],
       [80, 73, 21,  4],
       [10,  6, 90, 65],
       [15,  7, 16, 33],
       [55, 83, 50,  1]], dtype=int32)

# np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.<br>
https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [53]:
# code 
a

array([40, 46, 63, 47, 36, 58, 43, 31, 19, 52, 75, 64, 35, 95, 43],
      dtype=int32)

In [55]:
np.put(a,[0,1],[100,120])
a

array([100, 120,  63,  47,  36,  58,  43,  31,  19,  52,  75,  64,  35,
        95,  43], dtype=int32)

# np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.<br>
https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [56]:
# code
a

array([100, 120,  63,  47,  36,  58,  43,  31,  19,  52,  75,  64,  35,
        95,  43], dtype=int32)

In [57]:
np.delete(a,0)

array([120,  63,  47,  36,  58,  43,  31,  19,  52,  75,  64,  35,  95,
        43], dtype=int32)

## Set functions
    np.union1d
    np.intersect1d
    np.setdiff1d
    np.setxor1d

In [58]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
np.intersect1d(m,n)

array([3, 4, 5])

In [60]:
np.setdiff1d(m,n)

array([1, 2])

In [61]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

# np.clip
numpy.clip() function is used to Clip (limit) the values in an array.<br>
https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [62]:
# code
a

array([100, 120,  63,  47,  36,  58,  43,  31,  19,  52,  75,  64,  35,
        95,  43], dtype=int32)

In [63]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 63, 47, 36, 58, 43, 31, 25, 52, 75, 64, 35, 75, 43],
      dtype=int32)

# np.swapaxes
np.swapaxes() is used to interchange two axes (dimensions) of an array.

In [64]:
# code
f = np.arange(12).reshape(3,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
g = np.swapaxes(f,0,1) # Axis 0 = column, Axis 1 = row
g

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# np.random.uniform()
np.random.uniform() is used to generate random numbers from a uniform distribution (all values have equal probability within a range).

In [68]:
# code

x = np.random.uniform(1,100,(2,3))
x

array([[ 6.07088975, 36.90343744, 20.65666833],
       [27.29007144, 88.10611486, 44.60442322]])

# np.count_nonzero()
np.count_nonzero() is used to count the number of non-zero (non-False) elements in an array.

In [69]:
# code
y = np.array([0,1,2,0,3,0,5])

In [70]:
np.count_nonzero(y)

np.int64(4)

# Well Done!