# What is numpy ?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## Numpy Arrays Vs Python Sequences

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.<br>
* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.<br>
* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.<br>
* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating NumPy Array

In [1]:
# np.array
import numpy as np 

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
# 2D and 3D np.array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3D Array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,4]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 4]]]


In [4]:
# dtype

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
# with reshape

np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
# np.ones and np.zeros (it's is used to initialize value)

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# np.random (it's give random value between 0 and 1)

np.random.random((3,4))

array([[0.18717728, 0.02461812, 0.49794509, 0.55583484],
       [0.85037512, 0.50064306, 0.76471062, 0.11241496],
       [0.56361209, 0.76890429, 0.73695096, 0.75409658]])

In [10]:
# np.linspace (it is creates a list of numbers that are perfectly "even spaced" over a range you choose)

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

# Array Attributes

In [11]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(12).reshape(3,2,2)

a3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [12]:
# ndim (number of dimension) it show dimension like 1d, 2d, 3d....nd

a3.ndim

3

In [13]:
# shape (it show in dimension how many item will existence.)

print(a3.shape)
a3

(3, 2, 2)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [14]:
# size (it's show number of items)

print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [15]:
# itemsize (it specifies the size in byte of a single element(or item) in an array)

a3.itemsize

8

In [16]:
# dtype (it's show data type)

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


# Changing DataType

In [17]:
# astype (it reduce memory space and data type)

a3.astype(np.int32)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]], dtype=int32)

# Array Operations

In [18]:
# take two array and shape for perform operation

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
# scalar operations

# arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [20]:
# relational

a2 > 15
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [21]:
# vector operations
# arithmetic

a1 * a2
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Functions

In [22]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[17., 13., 41.],
       [59., 28., 77.],
       [74., 28., 37.]])

In [23]:
# max/min/sum/prod
# 0 -> col and 1 -> row

np.max(a1, axis = 1)

array([41., 77., 74.])

In [24]:
# mean/median/std/var

np.median(a1,axis=1)

array([17., 59., 37.])

In [25]:
# trigonometric functions

np.sin(a1)

array([[-0.96139749,  0.42016704, -0.15862267],
       [ 0.63673801,  0.27090579,  0.99952016],
       [-0.98514626,  0.27090579, -0.64353813]])

In [26]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)
np.dot(a2,a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [27]:
# log and exponents

np.exp(a1)

array([[2.41549528e+07, 4.42413392e+05, 6.39843494e+17],
       [4.20121040e+25, 1.44625706e+12, 2.75851345e+33],
       [1.37338298e+32, 1.44625706e+12, 1.17191424e+16]])

In [28]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[100.,   5.,   2.],
       [ 55.,  20.,  81.]])

# Indexing and Slicing

In [29]:
a1 = np.arange(10) # (1D Array)
a2 = np.arange(12).reshape(3,4) # 2D Array
a3 = np.arange(8).reshape(2,2,2) # 3D Array

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1[-1]

np.int64(9)

In [33]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
print(a2[2,3])

11


In [35]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
print(a3[1,0,1])

5


# Slicing

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a2[0,:]

array([0, 1, 2, 3])

In [41]:
a2[:,2]

array([ 2,  6, 10])

In [42]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [43]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [48]:
a2[1,::3]

array([4, 7])

In [50]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [51]:
a3 = np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [54]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [55]:
a3[0,1,:]

array([3, 4, 5])

In [57]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [58]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [59]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [60]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [62]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [65]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [66]:
# reshape
a2.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [67]:
# Transpose

np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [68]:
# ravel

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [69]:
# hprizontal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [71]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting

In [72]:
# horizontal spliting

a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [74]:
# vertical spliting

a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]